If:
  PathMatch: *\*.h

CompileFlags:
    Add: [-Wall, -Wextra, -Werror, -xc]

InlayHints:
  BlockEnd: Yes
  Designators: Yes
  Enabled: Yes
  ParameterNames: Yes
  DeducedTypes: Yes
  TypeNameLimit: 24

Hover:
  ShowAKA: Yes

Diagnostics:
  UnusedIncludes: Strict
  UnusedVariables: Strict
